export const DUMMY_ACTION_SUCCESS = "DUMMY_ACTION_SUCCESS";
export const DUMMY_ACTION_SAGA = "DUMMY_ACTION_SAGA";

export const GAME_SETUP_START = "GAME_SETUP_START";
export const GAME_SETUP = "GAME_SETUP";
export const GAME_SETUP_SUCCESS = "GAME_SETUP_SUCCESS";
export const GAME_SETUP_FAIL = "GAME_SETUP_FAIL";

export const MOVE_START = "MOVE_START";
export const MOVE = "MOVE";
export const MOVE_SUCCESS = "MOVE_SUCCESS";
export const MOVE_FAIL = "MOVE_FAIL";

export const SET_WINNER_START = "SET_WINNER_START";
export const SET_WINNER = "SET_WINNER";
export const SET_WINNER_SUCCESS = "SET_WINNER_SUCCESS";
export const SET_WINNER_FAIL = "SET_WINNER_FAIL";
